### ISSUE TITLE
Vault policy

### ISSUE THREAD

**Issue by avoidik** [oracle/kubernetes-vault-kms-plugin#1]
Hi,

Could you please confirm that following policy is sufficient to proceed with the solution?

```
path "transit/keys/kube-secret-enc-key" {
  capabilities = ["read"]
}
path "transit/encrypt/kube-secret-enc-key" {
  capabilities = ["update"]
}
path "transit/decrypt/kube-secret-enc-key" {
  capabilities = ["update"]
}
```

**Comment by vineet-garg** [comment]
@avoidik 
following is sufficient (key read permission is not required)
path "transit/encrypt/kube-secret-enc-key" {
  capabilities = ["update"]
}
path "transit/decrypt/kube-secret-enc-key" {
  capabilities = ["update"]
}
