### ISSUE TITLE
How does this deal with rotation of secrets and pod rotation?

### ISSUE THREAD

**Issue by ajohnstone** [oracle/kubernetes-vault-kms-plugin#2]
How does this deal with rotation of secrets and pod rotation?

**Comment by vineet-garg** [comment]
@ajohnstone Can you please elaborate on rotation on which secret and which pod are you talking about?

The encryption key can be directly rotated on vault without requiring any change on the API server or the kms plugin side.

**Comment by ajohnstone** [comment]
If hashicorp vault is the KMS provider and rotation of a secret occurs within vault or one of its backends? Then the pod using a kubernetes secret will only get the new secret if you kill the pod, I'm not aware of anything in kubernetes to aid with this?

Additionally there is a cacheSize...? Which a cache may not deal with a rotated secret?

**Comment by vineet-garg** [comment]
Hashicorp vault is used only to encrypt and decrypt a kubernetes secret or a resource in general. Secrets/resources are still stored in etcd.  
Details about how a KMS provider work:https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/

**Comment by ajohnstone** [comment]
Great thanks for clarifying @vineet-garg  👍
